version: "3.9"

services:
  docker-react:
    container_name: docker-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - ".:/app"
    ports:
      - "80:80"
      - "8080:80"